### ISSUE TITLE
How do I run the examples?

### ISSUE THREAD

**Issue by ameya98** [yuki-koyama/elasty#45]
I followed the build instructions, but I do not find any executables. I'm not familiar with CMake :)

**Comment by yuki-koyama** [comment]
Hi,

The CMake file defines an option named `ELASTY_EXAMPLES`. This option is `OFF` by default.

https://github.com/yuki-koyama/elasty/blob/b959790659968d3793f78c882bb39619c81886ce/CMakeLists.txt#L60

Please enable this option by using the command line option:
```sh
cmake -DELASTY_EXAMPLES=ON /path/to/the/repository
```
or using `ccmake`.

**Comment by ameya98** [comment]
Got it, thank you!
